apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubevault
  namespace: demo
  labels:
    app: my-kubevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kubevault
  template:
    metadata:
      labels:
        app: my-kubevault
    spec:
      serviceAccountName: my-kubevault-sa
      containers:
      - name: my-kubevault
        image: maximiano86/kubevault:0.0.2
        ports:
        - containerPort: 3000   
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true       
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "kubevault-password" 
