apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kubevault-password
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.demo.svc.cluster.local:8200"
    roleName: "k8s.a2f3db19-7ce6-45be-9793-25c4913e6cfa.demo.my-kubevault-role"
    objects: |
      - objectName: "kubevault-password"
        secretPath: "secret/data/kubevault-pass"
        secretKey: "password"
