apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: development

bases:
- ../../base/

patchesStrategicMerge:
- deployment.yaml
 
configMapGenerator:	
- name: csi-configmap
  literals:	
    - value1=DevConfigMapValue
