apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  template:
    spec:
      containers:
        - name: static-server
          image: hashicorp/http-echo:latest
          args:
            - -text="hello staging"
            - -listen=:8080
