apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: staging

namePrefix: staging-

bases:
- ../../base/

patchesStrategicMerge:
- deploy-staging.yaml
- service-staging.yaml
